package com.lin.lostandfound.entities.domain;

// Generated 2017-3-9 14:42:21 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Loginlog generated by hbm2java
 */
public class LoginLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String userName;
	private String osname;
	private String browserName;
	private String loginIp;
	private Date loginTime;
	private long uid;

	public LoginLog() {
	}

	public LoginLog(String userName, String loginIp, Date loginTime, long uid) {
		this.userName = userName;
		this.loginIp = loginIp;
		this.loginTime = loginTime;
		this.uid = uid;
	}

	public LoginLog(String userName, String osname, String browserName,
			String loginIp, Date loginTime, long uid) {
		this.userName = userName;
		this.osname = osname;
		this.browserName = browserName;
		this.loginIp = loginIp;
		this.loginTime = loginTime;
		this.uid = uid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getOsname() {
		return this.osname;
	}

	public void setOsname(String osname) {
		this.osname = osname;
	}

	public String getBrowserName() {
		return this.browserName;
	}

	public void setBrowserName(String browserName) {
		this.browserName = browserName;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Override
	public String toString() {
		return "LoginLog [id=" + id + ", userName=" + userName + ", osname="
				+ osname + ", browserName=" + browserName + ", loginIp="
				+ loginIp + ", loginTime=" + loginTime + ", uid=" + uid + "]";
	}
	
}
