package com.lin.lostandfound.entities.domain;

// Generated 2017-4-14 20:56:35 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String title;
	private String substance;
	private int status;
	private Date publishTime;

	public Notice() {
	}

	public Notice(String substance, int status, Date publishTime) {
		this.substance = substance;
		this.status = status;
		this.publishTime = publishTime;
	}

	public Notice(String title, String substance, int status, Date publishTime) {
		this.title = title;
		this.substance = substance;
		this.status = status;
		this.publishTime = publishTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubstance() {
		return this.substance;
	}

	public void setSubstance(String substance) {
		this.substance = substance;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	@Override
	public String toString() {
		return "Notice [id=" + id + ", title=" + title + ", substance="
				+ substance + ", status=" + status + ", publishTime="
				+ publishTime + "]";
	}

}
