package com.lin.lostandfound.entities.domain;

// Generated 2016-12-5 10:18:18 by Hibernate Tools 4.0.0

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * Pickthings generated by hbm2java
 */
public class PickThings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String thingsName;
	private String pickPlace;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date pickTime;
	private String thingsType;
	private String thingsNo;
	private String thingsImg;
	private String thingsDes;
	private String storagePlace;
	private String telPhone;
	private Date publishTime;
	private int status;
	private String userName;
	private long uid;

	public PickThings() {
	}
	
	public PickThings(String thingsName, String pickPlace, Date pickTime,
			String thingsType, String thingsDes, int status, String userName, long uid) {
		this.thingsName = thingsName;
		this.pickPlace = pickPlace;
		this.pickTime = pickTime;
		this.thingsType = thingsType;
		this.thingsDes = thingsDes;
		this.status = status;
		this.userName = userName;
		this.uid = uid;
	}

	public PickThings(String thingsName, String pickPlace, Date pickTime,
			String thingsType, String thingsNo, String thingsImg,
			String thingsDes, String storagePlace, String telPhone,
			Date publishTime, int status, String userName, long uid) {
		this.thingsName = thingsName;
		this.pickPlace = pickPlace;
		this.pickTime = pickTime;
		this.thingsType = thingsType;
		this.thingsNo = thingsNo;
		this.thingsImg = thingsImg;
		this.thingsDes = thingsDes;
		this.storagePlace = storagePlace;
		this.telPhone = telPhone;
		this.publishTime = publishTime;
		this.status = status;
		this.userName = userName;
		this.uid = uid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getThingsName() {
		return this.thingsName;
	}

	public void setThingsName(String thingsName) {
		this.thingsName = thingsName;
	}

	public String getPickPlace() {
		return this.pickPlace;
	}

	public void setPickPlace(String pickPlace) {
		this.pickPlace = pickPlace;
	}

	public Date getPickTime() {
		return this.pickTime;
	}

	public void setPickTime(Date pickTime) {
		this.pickTime = pickTime;
	}

	public String getThingsType() {
		return this.thingsType;
	}

	public void setThingsType(String thingsType) {
		this.thingsType = thingsType;
	}

	public String getThingsNo() {
		return this.thingsNo;
	}

	public void setThingsNo(String thingsNo) {
		this.thingsNo = thingsNo;
	}

	public String getThingsImg() {
		return this.thingsImg;
	}

	public void setThingsImg(String thingsImg) {
		this.thingsImg = thingsImg;
	}

	public String getThingsDes() {
		return this.thingsDes;
	}

	public void setThingsDes(String thingsDes) {
		this.thingsDes = thingsDes;
	}

	public String getStoragePlace() {
		return this.storagePlace;
	}

	public void setStoragePlace(String storagePlace) {
		this.storagePlace = storagePlace;
	}

	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Override
	public String toString() {
		return "PickThings [id=" + id + ", thingsName=" + thingsName
				+ ", pickPlace=" + pickPlace + ", pickTime=" + pickTime
				+ ", thingsType=" + thingsType + ", thingsNo=" + thingsNo
				+ ", thingsImg=" + thingsImg + ", thingsDes=" + thingsDes
				+ ", storagePlace=" + storagePlace + ", telPhone=" + telPhone
				+ ", publishTime=" + publishTime + ", status=" + status
				+ ", userName=" + userName + ", uid=" + uid + "]";
	}
	
}
